// Generated by scripts/extract_cursor_exhaust.py
MERGE (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
SET s.captured_at_utc = '2026-03-10T03:29:16Z', s.schema_version = 'token-proxy.cursor-exhaust.v1', s.routing_visibility = 'partially_known', s.per_turn_status = 'unknown', s.routing_visibility_reason = 'Ensemble/single-model preference artifacts are available, but runtime per-turn routing decisions are not.', s.per_turn_reason = 'No authoritative per-turn model identifier found in captured local artifacts.'
SET s.plan_exec_use_chat_model = false, s.new_chat_model_auto_switch_applied = null
;

MERGE (m:CandidateModel {name: 'default'})
WITH m
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:CANDIDATE_MODEL]->(m);

MERGE (m:CandidateModel {name: 'gemini-3-flash'})
WITH m
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:CANDIDATE_MODEL]->(m);

MERGE (m:CandidateModel {name: 'gpt-5.1-codex'})
WITH m
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:CANDIDATE_MODEL]->(m);

MERGE (m:CandidateModel {name: 'gpt-5.1-codex-max'})
WITH m
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:CANDIDATE_MODEL]->(m);

MERGE (m:CandidateModel {name: 'gpt-5.2'})
WITH m
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:CANDIDATE_MODEL]->(m);

MERGE (r:CursorRuntimeSession {name: '20260309T082244'})
WITH r
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:DERIVED_FROM_RUNTIME]->(r);

MERGE (w:CursorWindow {name: 'window1'})
SET w.codex_log_exists = true, w.codex_log_lines = 8403, w.claude_log_exists = true, w.claude_log_lines = 2
WITH w
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:OBSERVED_WINDOW]->(w);

MERGE (w:CursorWindow {name: 'window2'})
SET w.codex_log_exists = true, w.codex_log_lines = 14865, w.claude_log_exists = true, w.claude_log_lines = 4
WITH w
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:OBSERVED_WINDOW]->(w);

MERGE (w:CursorWindow {name: 'window3'})
SET w.codex_log_exists = true, w.codex_log_lines = 48, w.claude_log_exists = true, w.claude_log_lines = 4
WITH w
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:OBSERVED_WINDOW]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-2cfda1ee-45ff-40cf-90ef-e592a748041f'})
SET p.file = 'Cursor-2cfda1ee-45ff-40cf-90ef-e592a748041f', p.app_name = 'Cursor', p.workspace_name = '.hammerspoon', p.timestamp = 1773105432887
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: '.hammerspoon'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-2cfda1ee-45ff-40cf-90ef-e592a748041f'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-74d93dbe-90cf-43a9-9177-cae3b86e08c2'})
SET p.file = 'Cursor-74d93dbe-90cf-43a9-9177-cae3b86e08c2', p.app_name = 'Cursor', p.workspace_name = '.hammerspoon', p.timestamp = 1773098917256
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: '.hammerspoon'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-74d93dbe-90cf-43a9-9177-cae3b86e08c2'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-37ad84b6-dd4a-49e4-b0a8-2658ed98751f'})
SET p.file = 'Cursor-37ad84b6-dd4a-49e4-b0a8-2658ed98751f', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1773098914516
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-37ad84b6-dd4a-49e4-b0a8-2658ed98751f'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-8338fa0f-5db0-4b09-ade6-719ad905b7a7'})
SET p.file = 'Cursor-8338fa0f-5db0-4b09-ade6-719ad905b7a7', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1773078409857
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-8338fa0f-5db0-4b09-ade6-719ad905b7a7'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-8c663b4d-1ccb-46ff-b16d-388a2c1d76e8'})
SET p.file = 'Cursor-8c663b4d-1ccb-46ff-b16d-388a2c1d76e8', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1773078406083
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-8c663b4d-1ccb-46ff-b16d-388a2c1d76e8'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-5f637afb-7696-45c2-8f24-2c3e3a276336'})
SET p.file = 'Cursor-5f637afb-7696-45c2-8f24-2c3e3a276336', p.app_name = 'Cursor', p.workspace_name = '.hammerspoon', p.timestamp = 1773066167442
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: '.hammerspoon'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-5f637afb-7696-45c2-8f24-2c3e3a276336'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-8bf3c167-9f10-4044-9c9e-33434c145df6'})
SET p.file = 'Cursor-8bf3c167-9f10-4044-9c9e-33434c145df6', p.app_name = 'Cursor', p.workspace_name = '.hammerspoon', p.timestamp = 1773021967937
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: '.hammerspoon'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-8bf3c167-9f10-4044-9c9e-33434c145df6'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-45236bf1-4eec-4387-a390-ffe586208e03'})
SET p.file = 'Cursor-45236bf1-4eec-4387-a390-ffe586208e03', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1773021964482
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-45236bf1-4eec-4387-a390-ffe586208e03'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-ef2d76f3-2973-4f94-b2f9-c30a9f350b22'})
SET p.file = 'Cursor-ef2d76f3-2973-4f94-b2f9-c30a9f350b22', p.app_name = 'Cursor', p.workspace_name = '.hammerspoon', p.timestamp = 1773014676869
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: '.hammerspoon'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-ef2d76f3-2973-4f94-b2f9-c30a9f350b22'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-5a9a619e-a055-4342-b523-cf00dba44522'})
SET p.file = 'Cursor-5a9a619e-a055-4342-b523-cf00dba44522', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1773014673842
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-5a9a619e-a055-4342-b523-cf00dba44522'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-a95839df-473a-466a-9baa-76cd576ed8bc'})
SET p.file = 'Cursor-a95839df-473a-466a-9baa-76cd576ed8bc', p.app_name = 'Cursor', p.workspace_name = '.hammerspoon', p.timestamp = 1773012645606
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: '.hammerspoon'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-a95839df-473a-466a-9baa-76cd576ed8bc'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-8de0f85c-49f9-4624-a117-b5bc2ccb11d9'})
SET p.file = 'Cursor-8de0f85c-49f9-4624-a117-b5bc2ccb11d9', p.app_name = 'Cursor', p.workspace_name = '.hammerspoon', p.timestamp = 1773011969651
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: '.hammerspoon'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-8de0f85c-49f9-4624-a117-b5bc2ccb11d9'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-26c1b114-c8a7-4f89-b060-2036df21f344'})
SET p.file = 'Cursor-26c1b114-c8a7-4f89-b060-2036df21f344', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1773011782538
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-26c1b114-c8a7-4f89-b060-2036df21f344'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-dc0c7a38-4c58-442a-8cb9-ad86453f2ef6'})
SET p.file = 'Cursor-dc0c7a38-4c58-442a-8cb9-ad86453f2ef6', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1772986011513
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-dc0c7a38-4c58-442a-8cb9-ad86453f2ef6'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-6b2062f7-1bfa-48c6-9f67-b1550c7e59b8'})
SET p.file = 'Cursor-6b2062f7-1bfa-48c6-9f67-b1550c7e59b8', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1772954697027
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-6b2062f7-1bfa-48c6-9f67-b1550c7e59b8'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-8b9b40cb-af99-4998-9eb2-fc3828e3a568'})
SET p.file = 'Cursor-8b9b40cb-af99-4998-9eb2-fc3828e3a568', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1772954693071
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-8b9b40cb-af99-4998-9eb2-fc3828e3a568'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-a3287f13-e466-40b3-a697-3e6c45ff0466'})
SET p.file = 'Cursor-a3287f13-e466-40b3-a697-3e6c45ff0466', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1772941835539
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-a3287f13-e466-40b3-a697-3e6c45ff0466'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-98d0da01-70c5-4e15-8b78-8a872ee63c49'})
SET p.file = 'Cursor-98d0da01-70c5-4e15-8b78-8a872ee63c49', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1772937955173
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-98d0da01-70c5-4e15-8b78-8a872ee63c49'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-fecc5c2d-8424-4361-ab85-41729979309a'})
SET p.file = 'Cursor-fecc5c2d-8424-4361-ab85-41729979309a', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1772597127169
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-fecc5c2d-8424-4361-ab85-41729979309a'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-99c88a6c-e6bc-4795-ac3d-cbf5794d3cc1'})
SET p.file = 'Cursor-99c88a6c-e6bc-4795-ac3d-cbf5794d3cc1', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1772583992754
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-99c88a6c-e6bc-4795-ac3d-cbf5794d3cc1'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-53d63f52-e8e3-422b-bff3-30cdb1f466af'})
SET p.file = 'Cursor-53d63f52-e8e3-422b-bff3-30cdb1f466af', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1772335763400
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-53d63f52-e8e3-422b-bff3-30cdb1f466af'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-42040511-57db-4d9e-8716-e6432f529701'})
SET p.file = 'Cursor-42040511-57db-4d9e-8716-e6432f529701', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1772335536761
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-42040511-57db-4d9e-8716-e6432f529701'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-a933112b-d5c3-499e-9afc-7fd6b1482cd1'})
SET p.file = 'Cursor-a933112b-d5c3-499e-9afc-7fd6b1482cd1', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1772129427391
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-a933112b-d5c3-499e-9afc-7fd6b1482cd1'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-0be8c4d3-df68-4b1f-b793-e469e41a647c'})
SET p.file = 'Cursor-0be8c4d3-df68-4b1f-b793-e469e41a647c', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771868908558
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-0be8c4d3-df68-4b1f-b793-e469e41a647c'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-81c14e17-1525-4c63-a9eb-ec8b296c93d6'})
SET p.file = 'Cursor-81c14e17-1525-4c63-a9eb-ec8b296c93d6', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1771863063675
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-81c14e17-1525-4c63-a9eb-ec8b296c93d6'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-44221ab2-bca1-410c-9d34-b67ebe6ac4a9'})
SET p.file = 'Cursor-44221ab2-bca1-410c-9d34-b67ebe6ac4a9', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771860803209
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-44221ab2-bca1-410c-9d34-b67ebe6ac4a9'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-bd63410e-06a0-4923-a4ce-46c7df4f7443'})
SET p.file = 'Cursor-bd63410e-06a0-4923-a4ce-46c7df4f7443', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771811902864
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-bd63410e-06a0-4923-a4ce-46c7df4f7443'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-e5a4eefd-8893-4969-a98b-cf490dd81fe0'})
SET p.file = 'Cursor-e5a4eefd-8893-4969-a98b-cf490dd81fe0', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1771788536481
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-e5a4eefd-8893-4969-a98b-cf490dd81fe0'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-256b1660-1f3a-46a2-9a4f-e1096860b4d3'})
SET p.file = 'Cursor-256b1660-1f3a-46a2-9a4f-e1096860b4d3', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1771788328784
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-256b1660-1f3a-46a2-9a4f-e1096860b4d3'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-ac24a3c6-1be3-44e5-8d23-cc9acdb08930'})
SET p.file = 'Cursor-ac24a3c6-1be3-44e5-8d23-cc9acdb08930', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1771787659531
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-ac24a3c6-1be3-44e5-8d23-cc9acdb08930'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-07e88a15-e1b2-4862-9ee9-bea13109013d'})
SET p.file = 'Cursor-07e88a15-e1b2-4862-9ee9-bea13109013d', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771770064074
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-07e88a15-e1b2-4862-9ee9-bea13109013d'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-fa5b196e-d51e-4452-946a-a46cd6e6a45e'})
SET p.file = 'Cursor-fa5b196e-d51e-4452-946a-a46cd6e6a45e', p.app_name = 'Cursor', p.workspace_name = 'eudorus-pr3', p.timestamp = 1771724224265
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus-pr3'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-fa5b196e-d51e-4452-946a-a46cd6e6a45e'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-9d31f218-2781-4206-a644-dd7fb5c57ca3'})
SET p.file = 'Cursor-9d31f218-2781-4206-a644-dd7fb5c57ca3', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1771724164341
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-9d31f218-2781-4206-a644-dd7fb5c57ca3'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-262ff93c-4508-4488-928f-1f3e5e837999'})
SET p.file = 'Cursor-262ff93c-4508-4488-928f-1f3e5e837999', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771697298465
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-262ff93c-4508-4488-928f-1f3e5e837999'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-ca3d4791-2fdb-4dc3-ba8d-160ddf577737'})
SET p.file = 'Cursor-ca3d4791-2fdb-4dc3-ba8d-160ddf577737', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771632764722
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-ca3d4791-2fdb-4dc3-ba8d-160ddf577737'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-617756bd-eecd-4b20-ab73-2a2eddcc5655'})
SET p.file = 'Cursor-617756bd-eecd-4b20-ab73-2a2eddcc5655', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771631091331
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-617756bd-eecd-4b20-ab73-2a2eddcc5655'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-e64a7cb5-63aa-4481-938d-ec223e42afa6'})
SET p.file = 'Cursor-e64a7cb5-63aa-4481-938d-ec223e42afa6', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771621952142
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-e64a7cb5-63aa-4481-938d-ec223e42afa6'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-b0a29e4c-0ac6-4603-b474-34587a87849f'})
SET p.file = 'Cursor-b0a29e4c-0ac6-4603-b474-34587a87849f', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771610161531
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-b0a29e4c-0ac6-4603-b474-34587a87849f'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-211eb5a1-5c73-44a0-8a0a-f6d52e7a5f15'})
SET p.file = 'Cursor-211eb5a1-5c73-44a0-8a0a-f6d52e7a5f15', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771541992909
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-211eb5a1-5c73-44a0-8a0a-f6d52e7a5f15'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-b8e2947a-7fc8-444a-88b8-61443b567697'})
SET p.file = 'Cursor-b8e2947a-7fc8-444a-88b8-61443b567697', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771442966546
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-b8e2947a-7fc8-444a-88b8-61443b567697'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-3e662508-c080-4d79-bcec-5810701ccc5a'})
SET p.file = 'Cursor-3e662508-c080-4d79-bcec-5810701ccc5a', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771439964498
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-3e662508-c080-4d79-bcec-5810701ccc5a'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-657ed433-65dd-4886-995a-93840d53a0e9'})
SET p.file = 'Cursor-657ed433-65dd-4886-995a-93840d53a0e9', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771435505471
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-657ed433-65dd-4886-995a-93840d53a0e9'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-edd7be6e-46f5-449c-bc1d-e229f0025038'})
SET p.file = 'Cursor-edd7be6e-46f5-449c-bc1d-e229f0025038', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771423352238
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-edd7be6e-46f5-449c-bc1d-e229f0025038'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-a29c6c79-8476-43e4-8e22-5bb7082d72f8'})
SET p.file = 'Cursor-a29c6c79-8476-43e4-8e22-5bb7082d72f8', p.app_name = 'Cursor', p.workspace_name = 'eudorus', p.timestamp = 1771422299257
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'eudorus'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-a29c6c79-8476-43e4-8e22-5bb7082d72f8'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-973a23f6-a816-4627-96e0-7e6539fe158d'})
SET p.file = 'Cursor-973a23f6-a816-4627-96e0-7e6539fe158d', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1771422289299
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-973a23f6-a816-4627-96e0-7e6539fe158d'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-fb6befb8-1e74-45cb-b0e6-37db66e06ff2'})
SET p.file = 'Cursor-fb6befb8-1e74-45cb-b0e6-37db66e06ff2', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1770068061782
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-fb6befb8-1e74-45cb-b0e6-37db66e06ff2'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-62c21229-eb9c-4a49-b1b3-185e62d23ac7'})
SET p.file = 'Cursor-62c21229-eb9c-4a49-b1b3-185e62d23ac7', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1769988032107
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-62c21229-eb9c-4a49-b1b3-185e62d23ac7'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-3e5ac8cb-786a-42f5-b2e7-3ae752b70db7'})
SET p.file = 'Cursor-3e5ac8cb-786a-42f5-b2e7-3ae752b70db7', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1769987368443
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-3e5ac8cb-786a-42f5-b2e7-3ae752b70db7'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-c496beee-ef7c-4a2e-928a-6331a2460a3a'})
SET p.file = 'Cursor-c496beee-ef7c-4a2e-928a-6331a2460a3a', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1769717291782
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-c496beee-ef7c-4a2e-928a-6331a2460a3a'})
MERGE (p)-[:WORKSPACE]->(w);

MERGE (p:CursorPairingSession {id: 'Cursor-db782e3c-2122-43d6-8305-d75d2ed773ae'})
SET p.file = 'Cursor-db782e3c-2122-43d6-8305-d75d2ed773ae', p.app_name = 'Cursor', p.workspace_name = 'Cursor', p.timestamp = 1769709697959
WITH p
MATCH (s:CursorExhaustSnapshot {id: 'cursor-exhaust-20260310T032916Z'})
MERGE (s)-[:HAS_PAIRING_SESSION]->(p);

MERGE (w:Workspace {name: 'Cursor'})
WITH w
MATCH (p:CursorPairingSession {id: 'Cursor-db782e3c-2122-43d6-8305-d75d2ed773ae'})
MERGE (p)-[:WORKSPACE]->(w);
